"""Publish a built mannequin as engine content.

    python3 tools/blender/mannequin/publish_mannequin.py \\
        --build <build_mannequin.py --out dir> \\
        --bakery build_release/tools/bakery/vkr_bakery [--content <dir>]

Cooks the glTF with explicit Bakery tool runs: the mesh in bundle mode, so
its materials sit in ./materials and its textures in ./textures beside the
.vkb, every source-image texture a material names into its .vkt, and the
animation bank. It then replaces the content directory (default
assets/characters/mannequin) with the source glTF, the cooked files, the clip
table and the credits notice, and writes the FPS module's generated clip
header and the engine content list. Nothing else in the repository changes.
"""

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


REPO = Path(__file__).resolve().parents[3]
CONTENT = "assets/characters/mannequin"
HEADER = "scripts/fps/src/fps_mannequin.h"
CONTENT_LIST = "cmake/vkr_mannequin_content.cmake"
TEXTURE_CLASSES = {"color_srgb": "color-srgb", "color_linear": "color-linear",
                   "normal_rg": "normal-rg", "data_mask": "data-mask"}

NOTICE = """# Mannequin credits

VKR's default mannequin is generated by `tools/blender/mannequin` from the
inputs pinned in `tools/blender/mannequin/sources.json`. It contains no Epic
Games content.

- **Body.** The realistic male body of Blender Studio's Human Base Meshes
  bundle v1.4.1, released under CC0 1.0 by Blender Studio. The helmet head,
  boots, shell design, textures, skeleton, skin weights, retargeting and
  materials are VKR's own.
- **Idle, backward, sidestep and crouch motion.** Retargeted from the
  100STYLE dataset (https://www.ianxmason.com/100style/), licensed under
  Creative Commons Attribution 4.0 International
  (https://creativecommons.org/licenses/by/4.0/). Credit: "The 100STYLE
  Dataset - Ian Mason". The clips were trimmed, looped, turned in place and
  retargeted with planted feet.
- **Forward walk, jog, run and jump motion.** Retargeted from the CMU
  Graphics Lab Motion Capture Database (http://mocap.cs.cmu.edu), subjects
  9, 13, 16 and 35. The data used in this project was obtained from
  mocap.cs.cmu.edu. The database was created with funding from NSF
  EIA-0196217.

A game that ships these animations must keep the 100STYLE credit above with
it, for example in its credits screen or bundled notices.
"""


def _run(command):
    result = subprocess.run([str(part) for part in command], capture_output=True, text=True)
    if result.returncode != 0:
        sys.stderr.write(result.stdout + result.stderr)
        raise RuntimeError("Command failed: " + " ".join(str(part) for part in command))
    return result.stdout


def _header(clips):
    lines = [
        "/* Generated by tools/blender/mannequin/publish_mannequin.py from",
        f"   {CONTENT}/mannequin.clips.json; do not edit. */",
        "#pragma once",
        "",
        "#include \"defines.h\"",
        "",
        f"#define FPS_MANNEQUIN_MESH \"{CONTENT}/mannequin.vkb\"",
        f"#define FPS_MANNEQUIN_ANIMATION \"{CONTENT}/mannequin.vka\"",
        "",
        "/* A loop's ground speed in metres per second and travel direction in the",
        "   mannequin's frame (x right, z backward: it faces -Z); duration in",
        "   seconds. One-shots have zero speed. */",
        "typedef struct FpsMannequinClip {",
        "  const char *name;",
        "  float32_t speed;",
        "  float32_t travel_x;",
        "  float32_t travel_z;",
        "  float32_t duration;",
        "  bool8_t loop;",
        "} FpsMannequinClip;",
        "",
        "static const FpsMannequinClip fps_mannequin_clips[] = {",
    ]
    for clip in clips:
        lines.append(f"    {{\"{clip['name']}\", {clip['speed']:.4f}f, {clip['travel'][0]:.4f}f, "
                     f"{clip['travel'][1]:.4f}f, {clip['duration']:.6f}f, "
                     f"{'true_v' if clip['loop'] else 'false_v'}}},")
    lines.append("};")
    lines.append("")
    return "\n".join(lines).replace("-0.0000f", "0.0000f")


ROOTS = ["mannequin.vkb", "mannequin.vka", "NOTICE.md"]


def _content_list(content, runtime):
    """The engine content's closure roots and every runtime file they reach:
    the mesh, bank and notice, the materials and the textures they name
    (with each source image's cooked .vkt). The source glTF and images stay
    in the content directory for re-cooking but are not packaged."""
    lines = ["# Generated by tools/blender/mannequin/publish_mannequin.py; do not edit.",
             "# The published mannequin for vkr_engine_content.cmake: its closure roots,",
             "# then the other files they reach.",
             "set(VKR_MANNEQUIN_INCLUDE"]
    lines += [f"    {content}/{name}" for name in ROOTS]
    lines[-1] += ")"
    lines.append("set(VKR_MANNEQUIN_FILES")
    lines += [f"    {content}/{name}" for name in runtime if name not in ROOTS]
    lines[-1] += ")"
    return "\n".join(lines) + "\n"


def _material_textures(material):
    """(image path, query) for every texture a material names."""
    for line in material.read_text(encoding="utf-8").splitlines():
        match = re.match(r"^\w+_texture=([^?]+)\?(.*)$", line)
        if match:
            query = dict(part.split("=", 1) for part in match.group(2).split("&") if "=" in part)
            yield (material.parent / match.group(1)).resolve(), query


def _cook_textures(bakery, staging):
    """Cook every source image a material names into `<image>.vkt`."""
    for material in sorted((staging / "materials").glob("*.mt")):
        for image, query in _material_textures(material):
            if image.suffix == ".vkt":
                continue
            texture_class = TEXTURE_CLASSES[query.get("tc", "color_srgb")]
            _run([bakery, "tool", "texture", "--output", str(image) + ".vkt", "--type", "2d",
                  "--layer", image, "--texture-class", texture_class])


def _runtime_files(destination):
    """Content-relative runtime files: roots, materials, named textures."""
    files = set(ROOTS)
    for material in sorted((destination / "materials").glob("*.mt")):
        files.add(str(material.relative_to(destination)))
        for image, _ in _material_textures(material):
            files.add(str(image.relative_to(destination)))
            if image.suffix != ".vkt":
                files.add(str(image.relative_to(destination)) + ".vkt")
    return sorted(files)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--build", required=True, type=Path)
    parser.add_argument("--bakery", required=True, type=Path)
    parser.add_argument("--content", default=CONTENT)
    args = parser.parse_args()
    content = args.content
    clips = json.loads((args.build / "mannequin.clips.json").read_text(encoding="utf-8"))

    with tempfile.TemporaryDirectory(prefix="mannequin-publish-") as staging_name:
        staging = Path(staging_name).resolve()
        shutil.copy2(args.build / "mannequin.gltf", staging / "mannequin.gltf")
        shutil.copy2(args.build / "mannequin.bin", staging / "mannequin.bin")
        shutil.copytree(args.build / "textures", staging / "textures")
        _run([args.bakery, "tool", "mesh", "--input", staging / "mannequin.gltf",
              "--output", staging / "mannequin.vkb", "--bundle-root", staging,
              "--import-id", "mannequin"])
        _run([args.bakery, "tool", "animation", "--input", staging / "mannequin.gltf",
              "--output", staging / "mannequin.vka"])
        _cook_textures(args.bakery, staging)
        destination = REPO / content
        if destination.exists():
            shutil.rmtree(destination)
        destination.mkdir(parents=True)
        # The source glTF and its images, the cooked mesh, bank, materials
        # and every texture the materials name.
        keep = ["mannequin.gltf", "mannequin.bin", "mannequin.vkb", "mannequin.vka"]
        keep += [f"materials/{p.name}" for p in sorted((staging / "materials").glob("*.mt"))]
        keep += [f"textures/{p.name}" for p in sorted((staging / "textures").glob("*")) if p.is_file()]
        for name in keep:
            (destination / name).parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(staging / name, destination / name)
    (destination / "mannequin.clips.json").write_text(json.dumps(clips, indent=2) + "\n", encoding="utf-8")
    (destination / "NOTICE.md").write_text(NOTICE, encoding="utf-8")
    runtime = _runtime_files(destination.resolve())
    missing = [name for name in runtime if not (destination / name).is_file()]
    if missing:
        raise RuntimeError("Published content lacks " + ", ".join(missing))
    if content == CONTENT:
        (REPO / HEADER).write_text(_header(clips["clips"]), encoding="utf-8")
        (REPO / CONTENT_LIST).write_text(_content_list(content, runtime), encoding="utf-8")
    for path in sorted(destination.rglob("*")):
        if path.is_file():
            print(f"{path.relative_to(REPO)}  {path.stat().st_size} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
