"""Publish a built mannequin as engine content.

    python3 tools/blender/mannequin/publish_mannequin.py \\
        --build <build_mannequin.py --out dir> \\
        --bakery build_release/tools/bakery/vkr_bakery

Cooks the GLB with explicit Bakery tool runs (the mesh in bundle mode, so its
materials sit in ./materials beside the .vkb, and the animation bank), then
replaces assets/characters/mannequin with the source GLB, the cooked files,
the clip table and the credits notice. It also writes the FPS module's
generated clip header. Nothing else in the repository changes.
"""

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


REPO = Path(__file__).resolve().parents[3]
CONTENT = "assets/characters/mannequin"
HEADER = "scripts/fps/src/fps_mannequin.h"

NOTICE = """# Mannequin credits

VKR's default mannequin is generated by `tools/blender/mannequin` from the
inputs pinned in `tools/blender/mannequin/sources.json`. It contains no Epic
Games content.

- **Body.** The MakeHuman base mesh, macro and region targets, default rig
  and default skin weights, released under CC0 1.0 by the MakeHuman project
  (makehumancommunity/makehuman at revision
  a8bc2d54ff0ac92e78ff71431b1023eda42bf482). The visor head, boots,
  skeleton, retargeting and materials are VKR's own.
- **Idle, backward, sidestep and crouch motion.** Retargeted from the
  100STYLE dataset (https://www.ianxmason.com/100style/), licensed under
  Creative Commons Attribution 4.0 International
  (https://creativecommons.org/licenses/by/4.0/). Credit: "The 100STYLE
  Dataset - Ian Mason". The clips were trimmed, looped, turned in place and
  retargeted with planted feet.
- **Forward walk, jog, run and jump motion.** Retargeted from the CMU
  Graphics Lab Motion Capture Database (http://mocap.cs.cmu.edu), subjects
  9, 13 and 35. The data used in this project was obtained from
  mocap.cs.cmu.edu. The database was created with funding from NSF
  EIA-0196217.

A game that ships these animations must keep the 100STYLE credit above with
it, for example in its credits screen or bundled notices.
"""


def _run(command):
    result = subprocess.run([str(part) for part in command], capture_output=True, text=True)
    if result.returncode != 0:
        sys.stderr.write(result.stdout + result.stderr)
        raise RuntimeError("Command failed: " + " ".join(str(part) for part in command))
    return result.stdout


def _header(clips):
    lines = [
        "/* Generated by tools/blender/mannequin/publish_mannequin.py from",
        f"   {CONTENT}/mannequin.clips.json; do not edit. */",
        "#pragma once",
        "",
        "#include \"defines.h\"",
        "",
        f"#define FPS_MANNEQUIN_MESH \"{CONTENT}/mannequin.vkb\"",
        f"#define FPS_MANNEQUIN_ANIMATION \"{CONTENT}/mannequin.vka\"",
        "",
        "/* A loop's ground speed in metres per second and travel direction in the",
        "   mannequin's frame (x right, z backward: it faces -Z); duration in",
        "   seconds. One-shots have zero speed. */",
        "typedef struct FpsMannequinClip {",
        "  const char *name;",
        "  float32_t speed;",
        "  float32_t travel_x;",
        "  float32_t travel_z;",
        "  float32_t duration;",
        "  bool8_t loop;",
        "} FpsMannequinClip;",
        "",
        "static const FpsMannequinClip fps_mannequin_clips[] = {",
    ]
    for clip in clips:
        lines.append(f"    {{\"{clip['name']}\", {clip['speed']:.4f}f, {clip['travel'][0]:.4f}f, "
                     f"{clip['travel'][1]:.4f}f, {clip['duration']:.6f}f, "
                     f"{'true_v' if clip['loop'] else 'false_v'}}},")
    lines.append("};")
    lines.append("")
    return "\n".join(lines).replace("-0.0000f", "0.0000f")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--build", required=True, type=Path)
    parser.add_argument("--bakery", required=True, type=Path)
    args = parser.parse_args()
    glb = args.build / "mannequin.glb"
    clips_path = args.build / "mannequin.clips.json"
    clips = json.loads(clips_path.read_text(encoding="utf-8"))

    with tempfile.TemporaryDirectory(prefix="mannequin-publish-") as staging_name:
        staging = Path(staging_name).resolve()
        shutil.copy2(glb, staging / "mannequin.glb")
        _run([args.bakery, "tool", "mesh", "--input", staging / "mannequin.glb",
              "--output", staging / "mannequin.vkb", "--bundle-root", staging,
              "--import-id", "mannequin"])
        _run([args.bakery, "tool", "animation", "--input", staging / "mannequin.glb",
              "--output", staging / "mannequin.vka"])
        destination = REPO / CONTENT
        if destination.exists():
            shutil.rmtree(destination)
        (destination / "materials").mkdir(parents=True)
        for name in ("mannequin.glb", "mannequin.vkb", "mannequin.vka"):
            shutil.copy2(staging / name, destination / name)
        for material in sorted((staging / "materials").glob("*.mt")):
            shutil.copy2(material, destination / "materials" / material.name)
    (destination / "mannequin.clips.json").write_text(json.dumps(clips, indent=2) + "\n", encoding="utf-8")
    (destination / "NOTICE.md").write_text(NOTICE, encoding="utf-8")
    (REPO / HEADER).write_text(_header(clips["clips"]), encoding="utf-8")
    for path in sorted(destination.rglob("*")):
        if path.is_file():
            print(f"{path.relative_to(REPO)}  {path.stat().st_size} bytes")
    print(REPO / HEADER)
    return 0


if __name__ == "__main__":
    sys.exit(main())
