#pragma once

#include <stdint.h>

#define VKR_SHEEN_MIN_ROUGHNESS 0.04f
#define VKR_SHEEN_MIN_NOV 0.0001f
#define VKR_SHEEN_ENERGY_LUT_SIZE 256u
#define VKR_SHEEN_LTC_LUT_SIZE 64u
#define VKR_SHEEN_LTC_LUT_TABLE_COUNT 4u
#define VKR_SHEEN_LTC_LUT_CHANNEL_COUNT 4u
#define VKR_SHEEN_ENERGY_LUT_TEXEL_COUNT \
  (VKR_SHEEN_ENERGY_LUT_SIZE * VKR_SHEEN_ENERGY_LUT_SIZE)
#define VKR_SHEEN_LTC_LUT_TABLE_TEXEL_COUNT \
  (VKR_SHEEN_LTC_LUT_SIZE * VKR_SHEEN_LTC_LUT_SIZE)
#define VKR_SHEEN_LTC_LUT_TABLE_BYTE_SIZE \
  (VKR_SHEEN_LTC_LUT_TABLE_TEXEL_COUNT * VKR_SHEEN_LTC_LUT_CHANNEL_COUNT * \
   sizeof(uint16_t))

/*
 * Immutable little-endian IEEE-754 half tables generated by
 * `vkr_sheen_cooker`. The R16F energy table uses sqrt(max(N.V,
 * VKR_SHEEN_MIN_NOV)) horizontally and normalized roughness [.04, 1]
 * vertically. It stores normalized directional Charlie albedo without
 * allocation reserves.
 *
 * The four 64² RGBA16F LTC tables use normalized roughness horizontally and
 * 1-sqrt(N.V) vertically. Tables 0 and 2 encode the two positive-orientation
 * inverse matrices as {log2(s), log2(k), shear, beta}. Table 1 stores
 * {mixture fraction A, relative reserve, absolute reserve, E normalization};
 * table 3 stores mixture fraction B in R and zero in GBA.
 */
extern const uint16_t
    vkr_sheen_energy_lut_pixels[VKR_SHEEN_ENERGY_LUT_TEXEL_COUNT];
extern const uint16_t vkr_sheen_ltc_lut_pixels[VKR_SHEEN_LTC_LUT_TABLE_COUNT]
                                            [VKR_SHEEN_LTC_LUT_TABLE_TEXEL_COUNT *
                                             VKR_SHEEN_LTC_LUT_CHANNEL_COUNT];
