#pragma once

#include "defines.h"

/* Stable diagnostic codes. A code never changes meaning or severity; retired
 * codes stay reserved. `vkr_bakery help diag <code>` prints the description. */
typedef enum VkrBakeryDiag {
  VKR_BAKERY_DIAG_CLI_USAGE = 0,
  VKR_BAKERY_DIAG_CLI_UNKNOWN_SUBCOMMAND,
  VKR_BAKERY_DIAG_REC_UNKNOWN_FIELD,
  VKR_BAKERY_DIAG_REC_INVALID_VALUE,
  VKR_BAKERY_DIAG_REC_UNREADABLE,
  VKR_BAKERY_DIAG_REC_NO_PRODUCER,
  VKR_BAKERY_DIAG_IDX_MISSING_SOURCE,
  VKR_BAKERY_DIAG_IDX_UNREADABLE_SOURCE,
  VKR_BAKERY_DIAG_CACHE_UNWRITABLE,
  VKR_BAKERY_DIAG_CACHE_STORE_FAILED,
  VKR_BAKERY_DIAG_CACHE_PUBLISH_FAILED,
  VKR_BAKERY_DIAG_CACHE_CORRUPT,
  VKR_BAKERY_DIAG_SCHED_CRASHED,
  VKR_BAKERY_DIAG_SCHED_TIMEOUT,
  VKR_BAKERY_DIAG_SCHED_LAUNCH_FAILED,
  VKR_BAKERY_DIAG_SCHED_MISSING_PRODUCT,
  VKR_BAKERY_DIAG_TEX_FAILED,
  VKR_BAKERY_DIAG_MESH_FAILED,
  VKR_BAKERY_DIAG_MESH_MISSING_REFERENCE,
  VKR_BAKERY_DIAG_FONT_FAILED,
  VKR_BAKERY_DIAG_ANIM_FAILED,
  VKR_BAKERY_DIAG_COLL_FAILED,
  VKR_BAKERY_DIAG_TABLE_FAILED,
  VKR_BAKERY_DIAG_TABLE_REBUILD_REQUIRED,
  VKR_BAKERY_DIAG_BAKE_FAILED,
  VKR_BAKERY_DIAG_BAKE_NO_VOLUME,
  VKR_BAKERY_DIAG_PROBE_FAILED,
  VKR_BAKERY_DIAG_SHD_TOOLCHAIN_MISSING,
  VKR_BAKERY_DIAG_SHD_ERROR,
  VKR_BAKERY_DIAG_SHD_WARNING,
  VKR_BAKERY_DIAG_SHD_UNKNOWN_ENTRY,
  VKR_BAKERY_DIAG_SCRIPT_ERROR,
  VKR_BAKERY_DIAG_SCRIPT_WARNING,
  VKR_BAKERY_DIAG_SCRIPT_COMPILER_MISSING,
  VKR_BAKERY_DIAG_PROJ_FAILED,
  VKR_BAKERY_DIAG_PROJ_INVALID_REQUEST,
  VKR_BAKERY_DIAG_BUNDLE_FAILED,
  VKR_BAKERY_DIAG_BUNDLE_MISSING_RUNTIME,
  VKR_BAKERY_DIAG_SERVE_FAILED,
  VKR_BAKERY_DIAG_MAT_FAILED,
  VKR_BAKERY_DIAG_MAT_OVER_BUDGET,
  VKR_BAKERY_DIAG_COUNT
} VkrBakeryDiag;

typedef enum VkrBakerySeverity {
  VKR_BAKERY_SEVERITY_WARNING = 0,
  VKR_BAKERY_SEVERITY_ERROR,
} VkrBakerySeverity;

typedef struct VkrBakeryDiagInfo {
  const char *code;
  VkrBakerySeverity severity;
  const char *description;
} VkrBakeryDiagInfo;

const VkrBakeryDiagInfo *vkr_bakery_diag_info(VkrBakeryDiag diag);
/** Finds a code such as "VKR-SHD-0100"; NULL when unknown. */
const VkrBakeryDiagInfo *vkr_bakery_diag_find(const char *code);
uint32_t vkr_bakery_diag_count(void);
const VkrBakeryDiagInfo *vkr_bakery_diag_at(uint32_t index);
