# Writes the bake tools' SPIR-V modules (the ray-query transport, the BC page
# encoders and their decode kernel) into one header of byte arrays that
# vkr_bake_vulkan.cpp compiles in, so the bake tools carry their kernels and
# need no shader file at run time.
#
# cmake -DVKR_SPIRV_ARRAYS=<name>=<spv>,<name>=<spv>,...
#       -DVKR_SPIRV_OUTPUT=<header> -P vkr_bake_spirv_embed.cmake

function(vkr_bake_spirv_array name path out_text)
    file(READ "${path}" hex HEX)
    string(LENGTH "${hex}" hex_length)
    if(hex_length EQUAL 0)
        message(FATAL_ERROR "${path} is empty")
    endif()
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    # Sixteen bytes per line keep the header readable in a diff tool.
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n    " bytes
        "${bytes}")
    set(${out_text}
        "static const uint8_t ${name}[] = {\n    ${bytes}\n};\n\n"
        PARENT_SCOPE)
endfunction()

if(NOT VKR_SPIRV_ARRAYS OR NOT VKR_SPIRV_OUTPUT)
    message(FATAL_ERROR
        "vkr_bake_spirv_embed.cmake needs VKR_SPIRV_ARRAYS and VKR_SPIRV_OUTPUT")
endif()

set(header "// Generated by tools/bake/vkr_bake_spirv_embed.cmake; do not edit.\n")
string(APPEND header "#pragma once\n\n#include <cstdint>\n\n")
string(REPLACE "," ";" arrays "${VKR_SPIRV_ARRAYS}")
foreach(array IN LISTS arrays)
    string(FIND "${array}" "=" split)
    if(split LESS 1)
        message(FATAL_ERROR "${array} is not <name>=<spv>")
    endif()
    string(SUBSTRING "${array}" 0 ${split} name)
    math(EXPR path_start "${split} + 1")
    string(SUBSTRING "${array}" ${path_start} -1 path)
    vkr_bake_spirv_array(${name} "${path}" array_text)
    string(APPEND header "${array_text}")
endforeach()
file(WRITE "${VKR_SPIRV_OUTPUT}" "${header}")
