/* Generated by tools/blender/mannequin/publish_mannequin.py from
   assets/characters/mannequin/mannequin.clips.json; do not edit. */
#pragma once

#include "defines.h"

#define FPS_MANNEQUIN_MESH "assets/characters/mannequin/mannequin.vkb"
#define FPS_MANNEQUIN_ANIMATION "assets/characters/mannequin/mannequin.vka"

/* A loop's ground speed in metres per second and travel direction in the
   mannequin's frame (x right, z backward: it faces -Z); duration in
   seconds. One-shots have zero speed. */
typedef struct FpsMannequinClip {
  const char *name;
  float32_t speed;
  float32_t travel_x;
  float32_t travel_z;
  float32_t duration;
  bool8_t loop;
} FpsMannequinClip;

static const FpsMannequinClip fps_mannequin_clips[] = {
    {"Crouch_Idle", 0.0000f, 0.0000f, -1.0000f, 5.000000f, true_v},
    {"Crouch_Walk_Bwd", 0.4763f, 0.0000f, 1.0000f, 1.300000f, true_v},
    {"Crouch_Walk_Fwd", 0.6306f, 0.0000f, -1.0000f, 1.233333f, true_v},
    {"Crouch_Walk_Left", 0.4409f, -1.0000f, 0.0000f, 1.316667f, true_v},
    {"Crouch_Walk_Right", 0.5243f, 1.0000f, 0.0000f, 1.083333f, true_v},
    {"Idle", 0.0000f, 0.0000f, -1.0000f, 6.000000f, true_v},
    {"Jog_Bwd", 1.0456f, 0.0000f, 1.0000f, 0.650000f, true_v},
    {"Jog_Fwd", 3.3772f, 0.0000f, -1.0000f, 0.766667f, true_v},
    {"Jog_Left", 1.0178f, -1.0000f, 0.0000f, 0.733333f, true_v},
    {"Jog_Right", 1.3928f, 1.0000f, 0.0000f, 0.616667f, true_v},
    {"Jump_Land", 0.0000f, 0.0000f, -1.0000f, 0.733333f, false_v},
    {"Jump_Loop", 0.0000f, 0.0000f, -1.0000f, 0.500000f, true_v},
    {"Jump_Start", 0.0000f, 0.0000f, -1.0000f, 0.433333f, false_v},
    {"Run_Fwd", 3.8063f, 0.0000f, -1.0000f, 0.800000f, true_v},
    {"Walk_Bwd", 0.6138f, 0.0000f, 1.0000f, 1.150000f, true_v},
    {"Walk_Fwd", 1.9049f, 0.0000f, -1.0000f, 0.966667f, true_v},
    {"Walk_Left", 0.4410f, -1.0000f, 0.0000f, 1.266667f, true_v},
    {"Walk_Right", 0.5538f, 1.0000f, 0.0000f, 1.183333f, true_v},
};
