#!/usr/bin/env python3
"""Convert the pinned Self Shadow LTC fit to VKR's two RGBA16F tables."""
from __future__ import annotations

import argparse
import hashlib
import re
import struct
from pathlib import Path

OUTPUT = Path(__file__).resolve().parent.parent / 'renderer/src/vkr_ltc_lut_data.inc'
SOURCE_SHA256 = '21071160163defd419b8f754ab604a8e60c44fcf539bfff9916e0e8e82316c1d'
COMMIT = '31e5e96b54f98f33098f8503003119ba2231a1c6'
SIZE = 64


def table(source: str, name: str) -> list[float]:
    start = source.index(f'var {name} = [')
    body = source[start:]
    body = body[body.index('[') + 1:body.index('];')]
    values = [float(value) for value in re.findall(
        r'[-+]?(?:\d+\.\d*|\d*\.\d+|\d+)(?:e[-+]?\d+)?', body)]
    assert len(values) == SIZE * SIZE * 4, (name, len(values))
    return values


def half_bits(value: float) -> int:
    return struct.unpack('<H', struct.pack('<e', value))[0]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, required=True,
                        help='fit/results/ltc.js from the pinned Self Shadow commit')
    parser.add_argument('--output', type=Path, default=OUTPUT)
    args = parser.parse_args()
    payload = args.source.read_bytes()
    digest = hashlib.sha256(payload).hexdigest()
    if digest != SOURCE_SHA256:
        parser.error('source digest does not match the pinned LTC fit')
    source = payload.decode('utf-8')
    tables = [table(source, 'g_ltc_1'), table(source, 'g_ltc_2')]
    lines = [
        '// Generated by tools/generate_ltc_lut.py. Do not hand edit.',
        '// Source: selfshadow/ltc_code fit/results/ltc.js',
        f'// Pinned commit: {COMMIT}; source SHA-256: {digest}.',
        '// Table 0: inverse LTC matrix m00,m20,m02,m22. Table 1: norm,Fresnel,unused,unused.',
        '{',
    ]
    for table_index, values in enumerate(tables):
        if table_index:
            lines.append('},')
            lines.append('{')
        for offset in range(0, len(values), 8):
            lines.append('    ' + ', '.join(f'0x{half_bits(value):04x}u'
                                              for value in values[offset:offset + 8]) + ',')
    lines.append('},')
    args.output.write_text('\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
