#include "vkr_atomic_file.h"
#include "vkr_dfg_lut.h"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

namespace {
constexpr uint32_t sample_count = 4096u;
constexpr double pi = 3.14159265358979323846;

uint32_t reverse_bits(uint32_t value) {
  value = (value << 16u) | (value >> 16u);
  value = ((value & 0x55555555u) << 1u) | ((value & 0xaaaaaaaau) >> 1u);
  value = ((value & 0x33333333u) << 2u) | ((value & 0xccccccccu) >> 2u);
  value = ((value & 0x0f0f0f0fu) << 4u) | ((value & 0xf0f0f0f0u) >> 4u);
  return ((value & 0x00ff00ffu) << 8u) | ((value & 0xff00ff00u) >> 8u);
}

uint32_t round_even(double value) {
  const uint32_t integer = static_cast<uint32_t>(std::floor(value));
  const double fraction = value - integer;
  return integer + (fraction > 0.5 || (fraction == 0.5 && (integer & 1u)));
}

uint16_t encode_half(double value) {
  if (value < std::ldexp(1.0, -14)) {
    return static_cast<uint16_t>(round_even(std::ldexp(value, 24)));
  }
  int exponent = 0;
  const double mantissa = std::frexp(value, &exponent);
  const uint32_t fraction = round_even((mantissa * 2.0 - 1.0) * 1024.0);
  return static_cast<uint16_t>(((exponent + 14) << 10) + fraction);
}

struct DiskSample {
  double x, y;
};
struct Integral {
  double a, b;
};

Integral integrate(double no_v, double roughness,
                   const std::vector<DiskSample> &disk) {
  if (roughness == 0.0) {
    const double f = std::pow(1.0 - no_v, 5.0);
    return {1.0 - f, f};
  }
  // The exact grazing endpoint is the limiting positive hemisphere value.
  no_v = std::max(no_v, 1e-5);
  const double vx = std::sqrt(1.0 - no_v * no_v);
  const double alpha = roughness * roughness;
  const double a2 = alpha * alpha;
  const double vh_length = std::sqrt(a2 * vx * vx + no_v * no_v);
  const double vhx = alpha * vx / vh_length;
  const double vhz = no_v / vh_length;
  const double blend = 0.5 * (1.0 + vhz);
  const double view_root = std::sqrt(a2 + (1.0 - a2) * no_v * no_v);
  Integral result = {};
  // Heitz 2018 visible-GGX disk sampling. V lies in XZ; the orthonormal
  // frame is T1=(0,1,0), T2=(-Vh.z,0,Vh.x), including the normal-view case.
  for (const DiskSample sample : disk) {
    const double t1 = sample.x;
    const double t2 =
        (1.0 - blend) * std::sqrt(1.0 - t1 * t1) + blend * sample.y;
    const double t3 = std::sqrt(std::max(0.0, 1.0 - t1 * t1 - t2 * t2));
    double hx = alpha * (-t2 * vhz + t3 * vhx);
    double hy = alpha * t1;
    double hz = std::max(0.0, t2 * vhx + t3 * vhz);
    const double inverse_length = 1.0 / std::sqrt(hx * hx + hy * hy + hz * hz);
    hx *= inverse_length;
    hz *= inverse_length;
    const double vo_h = std::max(0.0, vx * hx + no_v * hz);
    const double no_l = 2.0 * vo_h * hz - no_v;
    if (no_l <= 0.0)
      continue;
    const double light_root = std::sqrt(a2 + (1.0 - a2) * no_l * no_l);
    // G2/G1(view), after cancelling the visible-normal sampling PDF.
    const double weight =
        no_l * (no_v + view_root) / (no_l * view_root + no_v * light_root);
    const double m = 1.0 - vo_h;
    const double fresnel = m * m * m * m * m;
    result.a += weight * (1.0 - fresnel);
    result.b += weight * fresnel;
  }
  result.a /= disk.size();
  result.b /= disk.size();
  return result;
}
} // namespace

int main(int argc, char **argv) {
  if (argc != 2) {
    std::cerr << "Usage: vkr_dfg_cooker <output.inc>\n";
    return 2;
  }
  std::vector<DiskSample> disk(sample_count);
  for (uint32_t i = 0; i < sample_count; ++i) {
    const double radius = std::sqrt((i + 0.5) / sample_count);
    const double angle = 2.0 * pi * reverse_bits(i) / 4294967296.0;
    disk[i] = {radius * std::cos(angle), radius * std::sin(angle)};
  }
  std::ostringstream output;
  output
      << "// Generated by vkr_dfg_cooker: correlated Smith GGX, Schlick A/B.\n"
         "// 256x256 RG16F, 4096 visible-normal samples, sqrt(NoV)/roughness grid.\n"
         "// Regenerate both native renderers' immutable table together.\n";
  for (uint32_t y = 0; y < VKR_DFG_LUT_SIZE; ++y) {
    for (uint32_t x = 0; x < VKR_DFG_LUT_SIZE; ++x) {
      const Integral value =
          integrate(std::pow(double(x) / (VKR_DFG_LUT_SIZE - 1u), 2.0),
                    double(y) / (VKR_DFG_LUT_SIZE - 1u), disk);
      if (!std::isfinite(value.a + value.b) || value.a < 0.0 || value.b < 0.0 ||
          value.a + value.b > 1.000001 || value.a + value.b < 0.25) {
        std::cerr << "Invalid integral at " << x << ',' << y << '\n';
        return 1;
      }
      output << "0x" << std::hex << std::setw(4) << std::setfill('0')
             << encode_half(value.a) << ", 0x" << std::setw(4)
             << encode_half(value.b) << ',';
      output << ((x & 3u) == 3u ? '\n' : ' ');
    }
  }
  const std::string contents = output.str();
  std::ifstream previous(argv[1], std::ios::binary);
  const std::string existing((std::istreambuf_iterator<char>(previous)), {});
  if (existing == contents) {
    std::cout << "DFG unchanged\n";
    return 0;
  }
  if (!vkr_tools::write_file_atomic(argv[1], contents))
    return 1;
  std::cout << "DFG generated: " << VKR_DFG_LUT_SIZE << "x" << VKR_DFG_LUT_SIZE
            << " RG16F, " << sample_count << " samples/texel\n";
  return 0;
}
