if(NOT DEFINED VKR_SHADER_OUTPUT OR NOT DEFINED VKR_SHADER_INPUTS)
    message(FATAL_ERROR
        "VKR_SHADER_OUTPUT and VKR_SHADER_INPUTS are required")
endif()

string(REPLACE "|" ";" VKR_SHADER_INPUT_LIST "${VKR_SHADER_INPUTS}")
get_filename_component(VKR_SHADER_OUTPUT_DIR "${VKR_SHADER_OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${VKR_SHADER_OUTPUT_DIR}")
file(WRITE "${VKR_SHADER_OUTPUT}" "")

foreach(VKR_SHADER_INPUT IN LISTS VKR_SHADER_INPUT_LIST)
    if(NOT EXISTS "${VKR_SHADER_INPUT}")
        message(FATAL_ERROR "Shader aggregation input not found: ${VKR_SHADER_INPUT}")
    endif()
    file(READ "${VKR_SHADER_INPUT}" VKR_SHADER_SOURCE)
    file(APPEND "${VKR_SHADER_OUTPUT}" "${VKR_SHADER_SOURCE}\n")
endforeach()
