# Generated by tools/blender/mannequin/publish_mannequin.py; do not edit.
# The published mannequin for vkr_engine_content.cmake: its closure roots,
# then the other files they reach.
set(VKR_MANNEQUIN_INCLUDE
    assets/characters/mannequin/mannequin.vkb
    assets/characters/mannequin/mannequin.vka
    assets/characters/mannequin/NOTICE.md)
set(VKR_MANNEQUIN_FILES
    assets/characters/mannequin/materials/gltf_mat_95137e68ef96798b_0.mt
    assets/characters/mannequin/textures/9b51824141e57d20.png
    assets/characters/mannequin/textures/9b51824141e57d20.png.vkt
    assets/characters/mannequin/textures/ef60d48121ece415.png
    assets/characters/mannequin/textures/ef60d48121ece415.png.vkt
    assets/characters/mannequin/textures/mannequin_paired_metalrough.vkt
    assets/characters/mannequin/textures/mannequin_paired_normal.vkt)
set(VKR_MANNEQUIN_TEXTURES
    "assets/characters/mannequin/textures/9b51824141e57d20.png|data-mask"
    "assets/characters/mannequin/textures/ef60d48121ece415.png|color-srgb")
set(VKR_MANNEQUIN_TEXTURE_PAIRS
    "assets/characters/mannequin/textures/mannequin_normal.png|assets/characters/mannequin/textures/mannequin_orm.png|assets/characters/mannequin/textures/mannequin_paired_normal.vkt|assets/characters/mannequin/textures/mannequin_paired_metalrough.vkt|1|1")
