# A program can use only one of ASan, TSan and MSan. Keep legacy ASan/UBSan
# switches for existing caches; an explicit Debug profile replaces that default.
option(VKR_ENABLE_SANITIZERS "Enable ASan/UBSan in every configuration" OFF)
set(debug_default ON)
if(WIN32)
    set(debug_default OFF)
endif()
option(VKR_ENABLE_DEBUG_SANITIZERS "Enable default Debug ASan/UBSan" ${debug_default})
set(VKR_DEBUG_SANITIZER "default" CACHE STRING "Debug sanitizer profile")
set_property(CACHE VKR_DEBUG_SANITIZER PROPERTY STRINGS default address thread memory leak none)
if(NOT VKR_DEBUG_SANITIZER MATCHES "^(default|address|thread|memory|leak|none)$")
    message(FATAL_ERROR "VKR_DEBUG_SANITIZER must be default, address, thread, memory, leak or none. ASan, TSan and MSan cannot be combined.")
endif()
if(VKR_ENABLE_SANITIZERS AND NOT VKR_DEBUG_SANITIZER STREQUAL "default")
    message(FATAL_ERROR "VKR_ENABLE_SANITIZERS applies ASan/UBSan to every configuration. Disable it before selecting a Debug sanitizer profile.")
endif()
if(NOT CMAKE_CONFIGURATION_TYPES AND NOT CMAKE_BUILD_TYPE STREQUAL "Debug" AND
   NOT VKR_DEBUG_SANITIZER MATCHES "^(default|none)$")
    message(FATAL_ERROR "Named sanitizer profiles require Debug. Use a separate Debug build tree.")
endif()

set(VKR_SANITIZE_DEPENDENCIES FALSE)
set(profile "${VKR_DEBUG_SANITIZER}")
if(profile STREQUAL "default")
    if(VKR_ENABLE_SANITIZERS OR (VKR_ENABLE_DEBUG_SANITIZERS AND
       (CMAKE_CONFIGURATION_TYPES OR CMAKE_BUILD_TYPE STREQUAL "Debug")))
        set(profile address)
    else()
        set(profile none)
    endif()
endif()
if(profile STREQUAL "none")
    return()
endif()

if(NOT CMAKE_C_COMPILER_ID MATCHES "^(Clang|AppleClang|GNU)$" OR
   NOT CMAKE_CXX_COMPILER_ID MATCHES "^(Clang|AppleClang|GNU)$" OR MSVC)
    message(FATAL_ERROR "VKR sanitizer profiles require the Clang or GCC driver with sanitizer runtimes for both C and C++.")
endif()
if(WIN32)
    if(NOT profile STREQUAL "address")
        message(FATAL_ERROR "${profile} sanitizer is unavailable on native Windows. TSan needs a supported Unix toolchain; MSan needs Linux/FreeBSD/NetBSD; LSan needs a supported non-Windows runtime.")
    endif()
    if(CMAKE_MSVC_RUNTIME_LIBRARY STREQUAL "MultiThreaded")
        message(FATAL_ERROR "Windows Clang ASan/UBSan requires the DLL CRT and matching dependencies. Use a separate tree with x64-windows-static-md or x64-windows dependencies.")
    endif()
endif()
if(profile STREQUAL "memory")
    if(NOT CMAKE_C_COMPILER_ID STREQUAL "Clang" OR
       NOT CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR
       NOT CMAKE_SYSTEM_NAME MATCHES "^(Linux|FreeBSD|NetBSD)$")
        message(FATAL_ERROR "MemorySanitizer requires Clang on Linux, FreeBSD or NetBSD, with instrumented external dependencies and C++ standard library.")
    endif()
endif()

# Check an executable link, not merely compiler flag acceptance. Cache by the
# toolchain and flags so incremental configuration does not rebuild probes.
include(CheckCSourceCompiles)
include(CheckCXXSourceCompiles)
include(CMakePushCheckState)
function(vkr_check_sanitizer flags extra_compile extra_link result)
    cmake_push_check_state(RESET)
    set(CMAKE_TRY_COMPILE_TARGET_TYPE EXECUTABLE)
    set(CMAKE_REQUIRED_FLAGS "${flags} ${extra_compile}")
    set(CMAKE_REQUIRED_LINK_OPTIONS "${flags}" ${extra_link})
    string(SHA256 signature "${CMAKE_C_COMPILER};${CMAKE_C_COMPILER_VERSION};${CMAKE_CXX_COMPILER};${CMAKE_CXX_COMPILER_VERSION};${CMAKE_C_COMPILER_TARGET};${CMAKE_CXX_COMPILER_TARGET};${CMAKE_SYSROOT};${CMAKE_OSX_ARCHITECTURES};${CMAKE_OSX_DEPLOYMENT_TARGET};${CMAKE_MSVC_RUNTIME_LIBRARY};${CMAKE_C_FLAGS};${CMAKE_CXX_FLAGS};${CMAKE_C_FLAGS_DEBUG};${CMAKE_CXX_FLAGS_DEBUG};${CMAKE_GENERATOR};${CMAKE_TOOLCHAIN_FILE};${CMAKE_EXE_LINKER_FLAGS};${flags};${extra_compile};${extra_link}")
    check_c_source_compiles("int main(int argc, char **argv) { return argv == 0 ? argc : 0; }" VKR_SAN_C_${signature})
    check_cxx_source_compiles("int main(int argc, char **argv) { return argv == nullptr ? argc : 0; }" VKR_SAN_CXX_${signature})
    if(VKR_SAN_C_${signature} AND VKR_SAN_CXX_${signature})
        set(${result} TRUE PARENT_SCOPE)
    else()
        set(${result} FALSE PARENT_SCOPE)
    endif()
    cmake_pop_check_state()
endfunction()

set(sanitizers "${profile},undefined")
set(extra_compile "")
set(extra_link "")
if(profile STREQUAL "memory")
    set(extra_compile "-fsanitize-memory-track-origins=2 -fPIE")
    set(extra_link -pie)
endif()
vkr_check_sanitizer("-fsanitize=${sanitizers}" "${extra_compile}" "${extra_link}" supported)
if(NOT supported)
    message(FATAL_ERROR "Cannot compile and link ${sanitizers} with this C/C++ toolchain. Install compatible sanitizer runtimes or select another VKR_DEBUG_SANITIZER profile. See CMakeFiles/CMakeConfigureLog.yaml for the failed probe.")
endif()
if(profile STREQUAL "address" AND NOT WIN32)
    vkr_check_sanitizer("-fsanitize=address,undefined,leak" "" "" leak_supported)
    if(leak_supported)
        set(sanitizers "address,undefined,leak")
    else()
        message(STATUS "LSan runtime unavailable; address profile retains ASan/UBSan")
    endif()
endif()

set(compile_flags "-fsanitize=${sanitizers}" -fno-omit-frame-pointer -g)
set(link_flags "-fsanitize=${sanitizers}" ${extra_link})
if(profile STREQUAL "memory")
    list(APPEND compile_flags -fsanitize-memory-track-origins=2 -fPIE)
endif()
if(VKR_ENABLE_SANITIZERS)
    add_compile_options(${compile_flags})
    add_link_options(${link_flags})
else()
    foreach(flag IN LISTS compile_flags)
        add_compile_options("$<$<CONFIG:Debug>:${flag}>")
    endforeach()
    foreach(flag IN LISTS link_flags)
        add_link_options("$<$<CONFIG:Debug>:${flag}>")
    endforeach()
endif()
# TSan needs instrumented synchronization and MSan needs propagated shadow
# state across library calls. Keep vendor optimization while retaining those
# profiles' instrumentation; normal Debug vendor policy is unchanged.
if(profile MATCHES "^(thread|memory)$")
    set(VKR_SANITIZE_DEPENDENCIES TRUE)
endif()
if(profile STREQUAL "memory")
    message(STATUS "MSan: in-tree dependencies are instrumented. Supply an instrumented C++ standard library and external dependencies via the toolchain; ordinary prebuilt libraries invalidate MSan coverage.")
endif()
message(STATUS "VKR sanitizers: ${sanitizers}; Debug-only unless VKR_ENABLE_SANITIZERS=ON")
