# Generates vkr_bakery_identity.h: one short content hash per producer group.
# A producer's identity is part of every action key, so editing a cooker, its
# cooked-format code or a vendored codec patch invalidates exactly that
# producer's cache entries. Run by a custom command whose DEPENDS lists the
# same files, so the header changes only when one of them does.
#
# Inputs: VKR_IDENTITY_SPEC (a file setting VKR_IDENTITY_GROUPS and, per group,
# VKR_IDENTITY_<GROUP>_FILES and VKR_IDENTITY_<GROUP>_EXTRA), VKR_IDENTITY_ROOT
# and VKR_IDENTITY_OUTPUT.

if(NOT DEFINED VKR_IDENTITY_SPEC OR NOT DEFINED VKR_IDENTITY_OUTPUT OR
   NOT DEFINED VKR_IDENTITY_ROOT)
    message(FATAL_ERROR "VKR_IDENTITY_SPEC, VKR_IDENTITY_ROOT and VKR_IDENTITY_OUTPUT are required")
endif()
include("${VKR_IDENTITY_SPEC}")

set(vkr_identity_header "#pragma once\n\n/* Generated by cmake/vkr_bakery_identity.cmake. */\n")
set(vkr_identity_all "")
foreach(group IN LISTS VKR_IDENTITY_GROUPS)
    set(digest_input "${VKR_IDENTITY_${group}_EXTRA}\n")
    set(files ${VKR_IDENTITY_${group}_FILES})
    list(SORT files)
    foreach(file IN LISTS files)
        if(NOT EXISTS "${file}")
            message(FATAL_ERROR "Identity input not found: ${file}")
        endif()
        file(SHA256 "${file}" file_hash)
        file(RELATIVE_PATH relative "${VKR_IDENTITY_ROOT}" "${file}")
        string(APPEND digest_input "${relative}:${file_hash}\n")
    endforeach()
    string(SHA256 group_hash "${digest_input}")
    string(SUBSTRING "${group_hash}" 0 16 group_hash)
    string(APPEND vkr_identity_all "${group}:${group_hash}\n")
    string(APPEND vkr_identity_header
        "#define VKR_BAKERY_IDENTITY_${group} \"${group_hash}\"\n")
endforeach()
string(SHA256 build_hash "${vkr_identity_all}")
string(SUBSTRING "${build_hash}" 0 16 build_hash)
string(APPEND vkr_identity_header
    "#define VKR_BAKERY_IDENTITY_BUILD \"${build_hash}\"\n")

set(existing "")
if(EXISTS "${VKR_IDENTITY_OUTPUT}")
    file(READ "${VKR_IDENTITY_OUTPUT}" existing)
endif()
if(NOT existing STREQUAL vkr_identity_header)
    file(WRITE "${VKR_IDENTITY_OUTPUT}" "${vkr_identity_header}")
endif()
